apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
data:
  zoo.cfg: |
    {{- include "zookeeper.servers" . | nindent 4 }}
    dataDir=/data
    dataLogDir=/datalog
    tickTime={{ .Values.tickTime }}
    initLimit={{ .Values.initLimit }}
    syncLimit={{ .Values.syncLimit }}
    autopurge.snapRetainCount={{ .Values.autoPurge.snapRetainCount }}
    autopurge.purgeInterval={{ .Values.autoPurge.purgeInterval }}
    maxClientCnxns={{ .Values.maxClientConnections }}
    standaloneEnabled={{ .Values.standaloneEnabled }}
    adminServer.enabled={{ .Values.adminServer.enabled }}
    4lw.commands.whitelist={{ include "zookeeper.commandWhitelist" . }}

    secureClientPort={{ .Values.ports.client }}
    sslQuorum=true
    serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
    ssl.quorum.keyStore.location=/pki/keystore.p12
    ssl.quorum.trustStore.location=/pki/truststore.p12
    ssl.keyStore.location=/pki/keystore.p12
    ssl.trustStore.location=/pki/truststore.p12

    {{- if .Values.extraConfig }}
    {{- range .Values.extraConfig }}
    {{ . | nindent 4 }}
    {{- end }}
    {{- end }}